export default {
  ROOT: "Root",
  NOT_FOUND: "NotFound",

  // Bottom Tab
  HOME_TAB: "HomeTab",
  LESSON_TAB: "LessonTab",
  EVENT_TAB: "EventTab",
  NEWS_TAB: "NewsTab",
  ACCOUNT_TAB: "AccountTab",

  // Screens
  AUTH: "Auth",
  LANDING: "Landing",
  LOGIN: "Login",
  SIGNUP: "Signup",
  FORGET_PASSWORD: "ForgetPassword",
  VERIFY_EMAIL: "VerifyEmail",
  RESET_PASSWORD: "ResetPassword",

  HOME_INDEX: "Home",
  LESSON_INDEX: "Lesson",
  FREE_INDEX: "FreeContent",
  MEMBERSHIP_INTRO: "MembershipIntro",
  BROWSE_ALL: "All",
  BROWSE_LIBRARY: "Library",
  LESSON_INTRO: "LessonIntro",
  VIDEO_LESSON: "VideoLesson",
  NOTE_EDITOR: "NoteEditor",
  PDF_READER: "PdfReader",
  EVENT_INDEX: "Event",
  EVENT_LIST: "EventList",
  EVENT_DETAIL: "EventDetail",
  NEWS_INDEX: "News",
  NEWS_DETAIL: "NewsDetail",
  ACCOUNT_INDEX: "Account",
  GUEST_INDEX: "Guest",
  MISSION: "Mission",
  BOOKMARK: "Bookmark",
  NOTIFICATION: "Notification",
  SEARCH: "Search",
  CHAT: "Chat",
  SETTINGS: "Settings",
  NOTIFICATION_SETTINGS: "NotificationSettings",
  THEME_SETTINGS: "ThemeSettings",
  EDIT_PROFILE: "EditProfile",
  PURCHASE_RECORD: "PurchaseRecord",
  MEMBERSHIP_PLAN: "MembershipPlan",
  WEB_PAYMENT: "WebPayment",
  WEB_EVENT: "WebEventForm",
  REDEEM_GIFT: "RedeemGift",
  TERMS_AND_CONDITIONS: "TermsAndConditions"
};
